items:
- uid: com.microsoft.azure.management.datalake.store.uploader._intentional_exception
  id: _intentional_exception
  parent: com.microsoft.azure.management.datalake.store.uploader
  href: com.microsoft.azure.management.datalake.store.uploader._intentional_exception.yml
  langs:
  - java
  name: IntentionalException
  fullName: com.microsoft.azure.management.datalake.store.uploader.IntentionalException
  type: Class
  source:
    remote:
      path: azure-mgmt-datalake-store-uploader/src/test/java/com/microsoft/azure/management/datalake/store/uploader/IntentionalException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: azure-mgmt-datalake-store-uploader/src/test/java/com/microsoft/azure/management/datalake/store/uploader/IntentionalException.java
    startLine: 12
  package: com.microsoft.azure.management.datalake.store.uploader
  summary: <p>An exception that we want our mocks to throw sometimes to test out various code paths. </p>
  syntax:
    content: public class IntentionalException extends CloudException
  inheritance:
  - java.lang.Object
  - Exception
  - com.microsoft.rest._rest_exception
  - com.microsoft.azure._cloud_exception
  inheritedMembers:
  - com.microsoft.azure._cloud_exception_1a3f1e2dea0d8094890be384020582c640
  - com.microsoft.azure._cloud_exception_1a09a1178a732322501fb26305c078a013
  - com.microsoft.azure._cloud_exception_1ae27e6c717f010c3f7941f2356f1b9949
  - com.microsoft.azure._cloud_exception_1aaa07127792b74506ee05d2eb4a0e8dff
  - com.microsoft.azure._cloud_exception_1ad2b736e14148c74d317e5ea2f19750bb
  - com.microsoft.azure._cloud_exception_1a030e3e16fccbe971cfff831986ed3895
  - com.microsoft.rest._rest_exception_1a8b86502c682e0b0e47f60b1c33b67b8f
  - com.microsoft.rest._rest_exception_1a8a0b21d2d492219e29a07567ff52b9cf
  - com.microsoft.rest._rest_exception_1ac00611a5b9a02b99e257f2407dc679d5
  - com.microsoft.rest._rest_exception_1ae3378da3ede0800826ccfe5f68532460
  - com.microsoft.azure._cloud_exception_1a35617fb86b4cbe5ebaba5c0e650e0994
  - com.microsoft.azure._cloud_exception_1a9749018041d780befdd8ccaba7176a56
  - com.microsoft.azure._cloud_exception_1a1be644eb573873f36de9559627c18581
references:
- uid: com.microsoft.azure._cloud_exception_1a3f1e2dea0d8094890be384020582c640
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException()
  fullName: com.microsoft.azure.CloudException.CloudException()
  type: Constructor
  summary: <p>Initializes a new instance of the ServiceException class. </p>
  syntax:
    content: public CloudException()
- uid: com.microsoft.azure._cloud_exception_1a09a1178a732322501fb26305c078a013
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException(final String message)
  fullName: com.microsoft.azure.CloudException.CloudException(final String message)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>The exception message. </p>
- uid: com.microsoft.azure._cloud_exception_1ae27e6c717f010c3f7941f2356f1b9949
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException(final String message, final Throwable cause)
  fullName: com.microsoft.azure.CloudException.CloudException(final String message, final Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message </p>
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception_1aaa07127792b74506ee05d2eb4a0e8dff
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException(final Throwable cause)
  fullName: com.microsoft.azure.CloudException.CloudException(final Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the ServiceException class.</p>

    <p></p>
  syntax:
    content: public CloudException(final Throwable cause)
    parameters:
    - id: cause
      type: fa00b19f
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception_1ad2b736e14148c74d317e5ea2f19750bb
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: getBody()
  fullName: CloudError com.microsoft.azure.CloudException.getBody()
  type: Method
  summary: >-
    <p>Gets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public CloudError getBody()
    return:
      type: com.microsoft.azure._cloud_error
      description: <p>the response body </p>
- uid: com.microsoft.azure._cloud_exception_1a030e3e16fccbe971cfff831986ed3895
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: getResponse()
  fullName: Response com.microsoft.azure.CloudException.getResponse()
  type: Method
  summary: >-
    <p>Gets information about the associated HTTP response.</p>

    <p></p>
  syntax:
    content: public Response getResponse()
    return:
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.rest._rest_exception_1a8b86502c682e0b0e47f60b1c33b67b8f
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException()
  fullName: com.microsoft.rest.RestException.RestException()
  type: Constructor
  summary: <p>Initializes a new instance of the AutoRestException class. </p>
  syntax:
    content: public RestException()
- uid: com.microsoft.rest._rest_exception_1a8a0b21d2d492219e29a07567ff52b9cf
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message)
  fullName: com.microsoft.rest.RestException.RestException(String message)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message)
    parameters:
    - id: message
      type: "26831127"
      description: <p>The exception message. </p>
- uid: com.microsoft.rest._rest_exception_1ac00611a5b9a02b99e257f2407dc679d5
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(Throwable cause)
    parameters:
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.rest._rest_exception_1ae3378da3ede0800826ccfe5f68532460
  parent: com.microsoft.rest._rest_exception
  href: com.microsoft.rest._rest_exception.yml
  name: RestException(String message, Throwable cause)
  fullName: com.microsoft.rest.RestException.RestException(String message, Throwable cause)
  type: Constructor
  summary: >-
    <p>Initializes a new instance of the AutoRestException class.</p>

    <p></p>
  syntax:
    content: public RestException(String message, Throwable cause)
    parameters:
    - id: message
      type: "26831127"
      description: <p>the exception message </p>
    - id: cause
      type: a04fafd7
      description: <p>exception that caused this exception to occur </p>
- uid: com.microsoft.azure._cloud_exception_1a35617fb86b4cbe5ebaba5c0e650e0994
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: setBody(CloudError body)
  fullName: void com.microsoft.azure.CloudException.setBody(CloudError body)
  type: Method
  summary: >-
    <p>Sets the HTTP response body.</p>

    <p></p>
  syntax:
    content: public void setBody(CloudError body)
    parameters:
    - id: body
      type: com.microsoft.azure._cloud_error
      description: <p>the response object </p>
- uid: com.microsoft.azure._cloud_exception_1a9749018041d780befdd8ccaba7176a56
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: setResponse(Response response)
  fullName: void com.microsoft.azure.CloudException.setResponse(Response response)
  type: Method
  summary: >-
    <p>Sets the HTTP response.</p>

    <p></p>
  syntax:
    content: public void setResponse(Response response)
    parameters:
    - id: response
      type: e9d34ed6
      description: <p>the HTTP response </p>
- uid: com.microsoft.azure._cloud_exception_1a1be644eb573873f36de9559627c18581
  parent: com.microsoft.azure._cloud_exception
  href: com.microsoft.azure._cloud_exception.yml
  name: toString()
  fullName: String com.microsoft.azure.CloudException.toString()
  type: Method
  syntax:
    content: public String toString()
    return:
      type: "26831127"
- uid: com.microsoft.azure._cloud_exception
  parent: com.microsoft.azure
  href: com.microsoft.azure._cloud_exception.yml
  name: CloudException
  fullName: com.microsoft.azure.CloudException
  type: Class
  summary: <p>Exception thrown for an invalid response with custom error information. </p>
  syntax:
    content: public class CloudException extends RestException
